apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=          # Base64 인코딩된 "admin"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # Base64 인코딩된 "password"
  POSTGRES_DB: a2lvc2s=            # Base64 인코딩된 "kiosk"
