# version: "3.8"
services:
  yolov10:
    image: python:3.8-slim
    container_name: yolov10-container
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8888:8888"
    command: ["python", "main.py"]
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile

